### ISSUE TITLE
Error Wrapping .apk signed with V2 Schema

### ISSUE THREAD

**Issue by Drain7** [msintuneappsdk/intune-app-wrapping-tool-android#17]
Hi,
I am getting the following error when trying to wrap and sign an .apk signed with v2 schema;

Failed to sign the output app because the input app was signed by Android Signature Scheme V2. This signing cannot currently be performed by the App Wrapping Tool. Please sign the wrapped app using the same tools used to sign the input app.
The application located at C:\*****.apk was successfully wrapped, but is not signed.

any update on this?

**Comment by msintuneappsdk** [comment]
The Android Signature Scheme V2 is not supported by the Android wrapper. If that’s what you’re looking to do - you can try doing the V2 signing of app manually after using the Intune AWT.

**Comment by Asutosh11** [comment]
You are giving a signed APK to the App wrapping tool as Input. It expects an unsigned App. Note: even debug APKs are signed with a debug signature.

I have written an article on checks to perform (including how to generate an unsigned APK) before starting the wrapping/signing procedure using the App wrapping tool.

You can have a look if you want. https://ironmonkey.in/prepare-your-android-app-for-wrapping-signing-using-intune-app-wrapping-tool/

**Comment by rygo-msft** [comment]
@Asutosh11 the App Wrapping Tool does support wrapping signed apks, but only using the V1 signing algorithm. The wrapping tool requires that the requested signing certificate and algorithm match those of the input apk, so the it will not sign an apk signed with the V2 or V3 signing algorithms. If you wish to wrap an apk signed using V2+ or to use a different certificate, you can do so by wrapping the apk without the signing parameters and manually signing the resulting apk using apksigner from the Android SDK.

If you are experiencing issues with the App Wrapping Tool blocking wrapping for signed apks when you have not provided signing parameters, please open an issue so that we can investigate as that is not expected to happen.
