### ISSUE TITLE
This tool vs Intune SDK

### ISSUE THREAD

**Issue by nilsi** [msintuneappsdk/intune-app-wrapping-tool-android#20]
We have developed an app using the Intune SDK, ADAL, and Graph.

After deploying the app from intune company portal we are getting stuck at a "this device needs to be managed screen" with an enroll now button.

After talking to Microsoft we found some interesting logs "[packagename] is not a managed app; disallowing prefetchCurrentFileEncryptionKey"
 
I'm now thinking of removing the SDK from our app. Try packaging it with this tool and deploying again.

What is the advantage of using this instead of the SDK and the opposite?

Thanks,
Nicklas

**Comment by aanavath** [comment]
This is a command line tool which is intended more for line-of-business type apps released for an organization's internal employees. The expectation is that these apps are simpler in functionality, tend to allow only a single log in and not multiple identities. The Intune SDK is used for public app store releases (but can also be used for internal apps) and apps with more complex scenarios with file sharing/saving and authentication. 

The advantage of using the Intune app wrapping tool is that there is minimal source code changes required to get key Intune app protection functionality. The main purpose of adding the Intune SDK or even wrapping with the Intune app wrapping tool is that you want to create and target that app with [Intune app protection policies](https://docs.microsoft.com/en-us/intune/app-protection-policies#create-an-app-protection-policy).

You could be seeing the "this device needs to be managed screen" with the enroll now button because the user has been targeted for device based conditional access. An IT admin can require this by following the documentation to [Set up device-based conditional access](https://docs.microsoft.com/en-us/intune/create-conditional-access-intune).

**Comment by msintuneappsdk** [comment]
Closing item.
